# Generated by Django 4.1 on 2022-12-20 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0002_remove_customer_date_of_birth'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Doctors', models.CharField(choices=[('Mollen', 'Mollen'), ('Joy', 'Joy'), ('Mark', 'Mark')], max_length=20, null=True)),
                ('Appointment', models.CharField(choices=[('Check-up', 'Check-up'), ('Weekly Appointments', 'Weekly Appointments'), ('Feeling unwell', 'Feeling unwell')], max_length=20, null=True)),
                ('Select_Time', models.TimeField(null=True)),
            ],
        ),
    ]
